import json

# ===== PART 1: Static code (setup, helpers, UI builders) =====
header = '''const API=window.location.origin.includes('localhost')?'http://localhost:5000/api':'/api';
let user=JSON.parse(localStorage.getItem('user')||'null'),token=localStorage.getItem('token')||'';
let cart=JSON.parse(localStorage.getItem('cart')||'[]'),products=[],currentProduct=null,shopPage=1;
let filters={cat:'',min:0,max:10000,sale:false,stock:false,sort:'newest'};
const $=id=>document.getElementById(id);
const fmt=n=>'₹'+Number(n).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const toast=(m,t='info')=>{const d=document.createElement('div');d.className='toast '+t;d.innerHTML=`<div class="flex items-center gap-2"><i class="fas fa-${t==='success'?'check-circle':t==='error'?'exclamation-circle':'info-circle'}"></i> ${m}</div>`;$('toast-container').appendChild(d);requestAnimationFrame(()=>d.classList.add('show'));setTimeout(()=>{d.classList.remove('show');setTimeout(()=>d.remove(),400)},3000)};
const api=async(p,o={})=>{const r=await fetch(API+p,{headers:{'Content-Type':'application/json',...(token?{'Authorization':'Bearer '+token}:{})},...o,body:o.body?JSON.stringify(o.body):undefined});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Failed');return d};

function buildNav(){
$('main-nav').innerHTML=`<div class="flex items-center justify-between px-4 md:px-10 lg:px-16 py-4"><div class="flex items-center gap-3 cursor-pointer" onclick="go('home')"><div class="w-10 h-10 bg-gradient-to-tr from-blue-500 to-pink-500 rounded-xl flex items-center justify-center pulse-glow"><i class="fas fa-play text-white text-xs"></i></div><span class="font-extrabold text-2xl tracking-tighter uppercase">OTT24<span class="text-pink-500 font-black">x</span>7</span></div><div class="hidden md:flex items-center gap-8">${['home','shop','about','contact','faq'].map(v=>`<button onclick="go('${v}')" class="text-xs font-bold text-gray-400 hover:text-white uppercase tracking-wider transition">${v[0].toUpperCase()+v.slice(1)}</button>`).join('')}</div><div class="flex items-center gap-4">${!user?`<button onclick="openDrawer('login-drawer')" class="hidden md:block text-[11px] font-bold text-gray-400 hover:text-white uppercase transition">Login / Register</button>`:`<div class="hidden md:flex items-center gap-2"><span class="text-xs font-bold text-pink-400">${user.username}</span><button onclick="logout()" class="text-[10px] font-bold text-gray-500 hover:text-red-400 uppercase">Logout</button></div>`}<div class="flex items-center gap-3 border-l border-gray-700 pl-4 cursor-pointer" onclick="openCart()"><div class="relative"><i class="fas fa-shopping-basket text-lg text-gray-300"></i><span id="cart-badge" class="absolute -top-2 -right-2 bg-pink-500 text-[9px] px-1.5 py-0.5 rounded-full font-black">0</span></div><span id="cart-total-nav" class="text-xs font-bold text-gray-400 hidden sm:inline">₹0.00</span></div><button class="md:hidden text-gray-400 hover:text-white" onclick="openDrawer('mobile-menu')"><i class="fas fa-bars text-lg"></i></button></div>`;
}
function buildDrawers(){
$('mobile-menu').innerHTML=`<div class="flex justify-between items-center mb-8"><span class="font-extrabold text-xl tracking-tighter uppercase">OTT24<span class="text-pink-500 font-black">x</span>7</span><button onclick="closeAll()" class="text-gray-400 hover:text-white"><i class="fas fa-times text-lg"></i></button></div><div class="space-y-1">${['home','shop','about','contact','faq'].map(v=>`<button onclick="go('${v}');closeAll()" class="block w-full text-left px-4 py-3 rounded-lg hover:bg-white/5 text-sm font-semibold">${v[0].toUpperCase()+v.slice(1)}</button>`).join('')}<hr class="border-gray-800 my-4">${!user?`<button onclick="openDrawer('login-drawer');closeAll()" class="block w-full text-left px-4 py-3 rounded-lg hover:bg-white/5 text-sm font-semibold text-pink-400">Login / Register</button>`:`<div class="px-4 py-3"><p class="text-sm font-bold text-pink-400">${user.username}</p><button onclick="logout();closeAll()" class="text-xs text-gray-500 mt-1">Logout</button></div>`}</div>`;
$('cart-drawer').innerHTML=`<div class="p-6 h-full flex flex-col"><div class="flex justify-between items-center mb-6 pb-4 border-b border-gray-800"><h2 class="text-lg font-bold flex items-center gap-2"><i class="fas fa-shopping-basket text-pink-500"></i> Your Cart <span id="cart-count-header" class="text-xs text-gray-500">(0)</span></h2><button onclick="closeAll()" class="text-xs font-bold text-gray-500 uppercase hover:text-white">Close</button></div><div id="cart-items" class="flex-1 overflow-y-auto space-y-4 pr-2"></div><div id="cart-footer" class="pt-4 border-t border-gray-800 hidden"><div class="flex justify-between items-center mb-4"><span class="text-sm font-bold text-gray-400">Subtotal</span><span id="cart-total" class="text-xl font-black text-white">₹0.00</span></div><button onclick="go('checkout');closeAll()" class="w-full bg-[#ff2d55] py-3.5 rounded-md font-bold text-xs uppercase tracking-widest hover:bg-pink-600 transition">Proceed to Checkout</button><button onclick="clearCart()" class="w-full mt-2 py-2 text-xs font-bold text-gray-500 uppercase hover:text-red-400 transition">Clear Cart</button></div>`;
$('login-drawer').innerHTML=`<div class="p-8"><div class="flex justify-between items-center mb-10"><h2 class="text-xl font-bold">Sign in</h2><button onclick="closeAll()" class="text-xs font-bold text-gray-500 uppercase hover:text-white">Close</button></div><form class="space-y-6" onsubmit="handleLogin(event)"><input type="email" id="le" placeholder="Email *" class="w-full bg-transparent border-b border-gray-800 py-3 outline-none text-sm focus:border-pink-500" required><input type="password" id="lp" placeholder="Password *" class="w-full bg-transparent border-b border-gray-800 py-3 outline-none text-sm focus:border-pink-500" required><button type="submit" class="w-full bg-[#ff2d55] py-3.5 font-bold text-xs uppercase tracking-widest rounded-sm hover:bg-pink-600 transition">Log in</button></form><div class="mt-8 text-center"><p class="text-xs text-gray-500 mb-4">No account?</p><button onclick="closeAll();openDrawer('register-drawer')" class="text-sm font-bold text-pink-500 hover:underline">Create Account</button></div>`;
$('register-drawer').innerHTML=`<div class="p-8"><div class="flex justify-between items-center mb-10"><h2 class="text-xl font-bold">Create Account</h2><button onclick="closeAll()" class="text-xs font-bold text-gray-500 uppercase hover:text-white">Close</button></div><form class="space-y-5" onsubmit="handleRegister(event)"><input type="text" id="ru" placeholder="Username *" class="w-full bg-transparent border-b border-gray-800 py-3 outline-none text-sm focus:border-pink-500" required minlength="3"><input type="email" id="re" placeholder="Email *" class="w-full bg-transparent border-b border-gray-800 py-3 outline-none text-sm focus:border-pink-500" required><input type="password" id="rp" placeholder="Password *" class="w-full bg-transparent border-b border-gray-800 py-3 outline-none text-sm focus:border-pink-500" required minlength="6"><input type="tel" id="rph" placeholder="Phone" class="w-full bg-transparent border-b border-gray-800 py-3 outline-none text-sm focus:border-pink-500"><button type="submit" class="w-full bg-[#ff2d55] py-3.5 font-bold text-xs uppercase tracking-widest rounded-sm hover:bg-pink-600 transition">Register</button></form><div class="mt-8 text-center"><p class="text-xs text-gray-500 mb-4">Have an account?</p><button onclick="closeAll();openDrawer('login-drawer')" class="text-sm font-bold text-pink-500 hover:underline">Sign in</button></div>`;
}

'''

# ===== VIEWS OBJECT =====
view_home = '''home:`<div id="home-view" class="view-content active"><header class="relative pt-16 pb-20 md:pt-24 md:pb-28 text-center px-4 overflow-hidden"><div class="absolute inset-0 opacity-20"><div class="absolute top-20 left-10 w-72 h-72 bg-pink-500/20 rounded-full blur-[100px]"></div><div class="absolute bottom-20 right-10 w-96 h-96 bg-blue-500/10 rounded-full blur-[100px]"></div><div class="relative z-10 max-w-5xl mx-auto"><div class="glass inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-green-400 text-[10px] font-bold tracking-widest uppercase mb-8"><span class="w-1.5 h-1.5 bg-green-400 rounded-full animate-pulse"></span> Instant Digital Delivery · Worldwide</div><h1 class="text-5xl md:text-7xl lg:text-[100px] font-extrabold mb-5 leading-[0.95] uppercase tracking-tighter">Premium Digital<br><span class="gradient-text">Subscriptions</span></h1><p class="text-gray-400 text-sm md:text-base max-w-xl mx-auto mb-10 font-medium">Get instant access to streaming platforms, software licenses, gaming subscriptions, and cloud storage at unbeatable prices.</p><div class="flex flex-wrap justify-center gap-4"><button onclick="go('shop')" class="bg-[#ff2d55] px-8 md:px-10 py-3.5 rounded-md font-bold text-[11px] uppercase tracking-wider hover:bg-pink-600 transition hover:scale-105">Browse All Products</button><a href="https://wa.me/919999999999" target="_blank" class="bg-[#25D366] px-8 md:px-10 py-3.5 rounded-md font-bold text-[11px] uppercase tracking-wider flex items-center gap-2 hover:bg-green-600 transition hover:scale-105"><i class="fab fa-whatsapp"></i> Whatsapp Us</a></div><div class="flex flex-wrap justify-center gap-x-8 gap-y-3 mt-14 pt-6 border-t border-gray-800/50"><div class="flex items-center gap-2 text-[10px] font-bold text-gray-400"><i class="fas fa-users text-pink-500"></i
