const mongoose = require('mongoose');
require('dotenv').config();

const connectDB = require('./config/db');
const Product = require('./models/Product');

const products = [
  {
    name: 'Netflix Premium 4K UHD 1 Month',
    description: 'Full access to Netflix Premium plan with 4K Ultra HD streaming on 4 screens simultaneously. Supports all devices. Instant email delivery with login credentials.',
    price: 249,
    originalPrice: 649,
    category: 'Streaming',
    iconClass: 'fas fa-film',
    iconColor: '#e50914',
    stock: 50,
    rating: 4.8,
    reviews: 1240,
    badge: '-62%',
    badgeColor: 'bg-red-600',
    inStock: true,
    onSale: true,
    features: ['4K Ultra HD', '4 Screens', 'All Devices', 'Instant Delivery'],
    tags: ['netflix', 'streaming', 'movies', 'series']
  },
  {
    name: 'Spotify Premium 3 Month',
    description: 'Ad-free music streaming with offline downloads and unlimited skips. Works on mobile, desktop, and smart speakers. Personal account with full ownership.',
    price: 199,
    originalPrice: 399,
    category: 'Streaming',
    iconClass: 'fab fa-spotify',
    iconColor: '#1db954',
    stock: 80,
    rating: 4.7,
    reviews: 890,
    badge: '-50%',
    badgeColor: 'bg-green-600',
    inStock: true,
    onSale: true,
    features: ['Ad-Free', 'Offline Mode', 'Unlimited Skips', 'High Quality Audio'],
    tags: ['spotify', 'music', 'streaming']
  },
  {
    name: '100GB Google Drive Storage 6 Month',
    description: 'Get 100GB of secure Google Drive cloud storage for 6 months via redeem link. Perfect for backing up photos, documents, and videos. Expands your existing Google account.',
    price: 299,
    originalPrice: 999,
    category: 'Storage',
    iconClass: 'fab fa-google-drive',
    iconColor: '#4285f4',
    stock: 120,
    rating: 4.5,
    reviews: 560,
    badge: '-70%',
    badgeColor: 'bg-red-600',
    inStock: true,
    onSale: true,
    features: ['100GB Storage', '6 Months', 'Redeem Link', 'Google Account'],
    tags: ['google', 'drive', 'cloud', 'storage']
  },
  {
    name: 'Adobe Creative Cloud 1 Month',
    description: 'Full access to all Adobe Creative Cloud apps including Photoshop, Illustrator, Premiere Pro, After Effects, and 20+ more professional tools. Enterprise license.',
    price: 599,
    originalPrice: 4200,
    category: 'Software',
    iconClass: 'fab fa-adobe',
    iconColor: '#ff0000',
    stock: 35,
    rating: 4.9,
    reviews: 2100,
    badge: '-86%',
    badgeColor: 'bg-purple-600',
    inStock: true,
    onSale: true,
    features: ['All Apps', 'Full Features', 'Cloud Storage', 'Monthly Plan'],
    tags: ['adobe', 'photoshop', 'design', 'video']
  },
  {
    name: 'NordVPN Premium 1 Year',
    description: 'Secure your internet with military-grade encryption. Access 5500+ servers in 60 countries. Strict no-logs policy. Supports 6 devices simultaneously.',
    price: 1299,
    originalPrice: 4999,
    category: 'VPN',
    iconClass: 'fas fa-shield-alt',
    iconColor: '#4687ff',
    stock: 45,
    rating: 4.6,
    reviews: 3400,
    badge: '-74%',
    badgeColor: 'bg-blue-600',
    inStock: true,
    onSale: true,
    features: ['5500+ Servers', 'No Logs', '6 Devices', 'Kill Switch'],
    tags: ['vpn', 'security', 'privacy', 'nordvpn']
  },
  {
    name: 'Xbox Game Pass Ultimate 3 Month',
    description: 'Access to 100+ high-quality games on console, PC, and cloud. Includes Xbox Live Gold, EA Play membership, and exclusive member discounts.',
    price: 799,
    originalPrice: 1999,
    category: 'Gaming',
    iconClass: 'fab fa-xbox',
    iconColor: '#107c10',
    stock: 30,
    rating: 4.8,
    reviews: 1500,
    badge: '-60%',
    badgeColor: 'bg-green-700',
    inStock: true,
    onSale: true,
    features: ['100+ Games', 'Cloud Gaming', 'Xbox Live Gold', 'EA Play'],
    tags: ['xbox', 'gaming', 'game pass', 'microsoft']
  },
  {
    name: 'PlayStation Plus Essential 1 Year',
    description: 'Online multiplayer access, 2 monthly games, exclusive discounts, and cloud storage for saves. Essential tier for PS4 and PS5 gamers.',
    price: 1499,
    originalPrice: 2999,
    category: 'Gaming',
    iconClass: 'fab fa-playstation',
    iconColor: '#003791',
    stock: 25,
    rating: 4.4,
    reviews: 980,
    badge: '-50%',
    badgeColor: 'bg-blue-700',
    inStock: true,
    onSale: true,
    features: ['Online Multiplayer', 'Free Games', 'Cloud Saves', 'Exclusive Discounts'],
    tags: ['playstation', 'ps5', 'ps4', 'gaming']
  },
  {
    name: 'Disney+ Hotstar VIP 1 Year',
    description: 'Watch Disney+ originals, Marvel, Star Wars, Pixar, and live sports including IPL. VIP plan with HD streaming on 1 screen. Indian content included.',
    price: 399,
    originalPrice: 399,
    category: 'Streaming',
    iconClass: 'fas fa-star',
    iconColor: '#1f80e0',
    stock: 100,
    rating: 4.3,
    reviews: 3200,
    badge: 'HOT',
    badgeColor: 'bg-orange-500',
    inStock: true,
    onSale: false,
    features: ['Disney+ Content', 'Live Sports', 'Marvel & Star Wars', 'HD Streaming'],
    tags: ['disney', 'hotstar', 'streaming', 'sports']
  },
  {
    name: 'Amazon Prime Video 1 Month',
    description: 'Unlimited streaming of movies and TV shows. Includes Prime delivery benefits, Prime Music, and Prime Reading. Works on all devices.',
    price: 149,
    originalPrice: 299,
    category: 'Streaming',
    iconClass: 'fab fa-amazon',
    iconColor: '#00a8e1',
    stock: 75,
    rating: 4.5,
    reviews: 1800,
    badge: '-50%',
    badgeColor: 'bg-blue-500',
    inStock: true,
    onSale: true,
    features: ['Movies & TV', 'Prime Delivery', 'Prime Music', 'All Devices'],
    tags: ['amazon', 'prime', 'streaming', 'movies']
  },
  {
    name: 'Microsoft Office 365 Lifetime',
    description: 'Lifetime access to Word, Excel, PowerPoint, Outlook, OneNote, and 1TB OneDrive storage. Works on 5 devices. Genuine license key delivered instantly.',
    price: 999,
    originalPrice: 4599,
    category: 'Software',
    iconClass: 'fab fa-microsoft',
    iconColor: '#d83b01',
    stock: 60,
    rating: 4.7,
    reviews: 4500,
    badge: '-78%',
    badgeColor: 'bg-orange-600',
    inStock: true,
    onSale: true,
    features: ['Lifetime', '5 Devices', '1TB Storage', 'All Apps'],
    tags: ['microsoft', 'office', 'productivity', 'windows']
  },
  {
    name: 'ExpressVPN 1 Year',
    description: 'Ultra-fast VPN servers in 94 countries. Best-in-class encryption and speed. Works on every device. 24/7 live chat support.',
    price: 1499,
    originalPrice: 7999,
    category: 'VPN',
    iconClass: 'fas fa-globe',
    iconColor: '#be161e',
    stock: 40,
    rating: 4.5,
    reviews: 2800,
    badge: '-81%',
    badgeColor: 'bg-red-700',
    inStock: true,
    onSale: true,
    features: ['94 Countries', 'Best Speed', 'All Devices', '24/7 Support'],
    tags: ['expressvpn', 'vpn', 'privacy', 'fast']
  },
  {
    name: 'Kaspersky Total Security 1 Year',
    description: 'Complete protection for your PC, Mac, and mobile. Includes antivirus, firewall, password manager, parental controls, and VPN. 3 device license.',
    price: 499,
    originalPrice: 1499,
    category: 'Antivirus',
    iconClass: 'fas fa-virus-slash',
    iconColor: '#00a651',
    stock: 55,
    rating: 4.4,
    reviews: 1200,
    badge: '-67%',
    badgeColor: 'bg-green-600',
    inStock: true,
    onSale: true,
    features: ['Antivirus', 'Firewall', 'Password Manager', '3 Devices'],
    tags: ['kaspersky', 'antivirus', 'security', 'protection']
  },
  {
    name: 'YouTube Premium 3 Month',
    description: 'Ad-free YouTube experience with background play and offline downloads. Includes YouTube Music Premium. Works on all devices.',
    price: 249,
    originalPrice: 399,
    category: 'Streaming',
    iconClass: 'fab fa-youtube',
    iconColor: '#ff0000',
    stock: 90,
    rating: 4.6,
    reviews: 2100,
    badge: '-38%',
    badgeColor: 'bg-red-500',
    inStock: true,
    onSale: true,
    features: ['Ad-Free', 'Background Play', 'Offline', 'YouTube Music'],
    tags: ['youtube', 'premium', 'music', 'streaming']
  },
  {
    name: 'Canva Pro 1 Year',
    description: 'Professional design tool with 100+ million stock photos, videos, and graphics. Brand kit, background remover, and team collaboration features.',
    price: 799,
    originalPrice: 3999,
    category: 'Software',
    iconClass: 'fas fa-palette',
    iconColor: '#00c4cc',
    stock: 70,
    rating: 4.8,
    reviews: 3500,
    badge: '-80%',
    badgeColor: 'bg-teal-500',
    inStock: true,
    onSale: true,
    features: ['100M+ Assets', 'Brand Kit', 'BG Remover', 'Team Features'],
    tags: ['canva', 'design', 'graphics', 'social media']
  },
  {
    name: '500GB Google Drive via Family Invite',
    description: 'Get 500GB Google Drive storage through family group invite delivered to your email. Permanent storage as long as you remain in the family group.',
    price: 799,
    originalPrice: 8999,
    category: 'Storage',
    iconClass: 'fab fa-google',
    iconColor: '#ea4335',
    stock: 40,
    rating: 4.3,
    reviews: 420,
    badge: '-91%',
    badgeColor: 'bg-red-600',
    inStock: true,
    onSale: true,
    features: ['500GB Storage', 'Family Invite', 'Permanent', 'Email Delivery'],
    tags: ['google', 'drive', 'storage', 'cloud']
  },
  {
    name: 'Steam Wallet Gift Card $20',
    description: 'Redeemable Steam Wallet code worth $20 USD. Instantly add funds to your Steam account to buy games, software, and DLC. Global activation.',
    price: 1699,
    originalPrice: 1699,
    category: 'Gaming',
    iconClass: 'fab fa-steam',
    iconColor: '#1b2838',
    stock: 100,
    rating: 4.9,
    reviews: 5600,
    badge: 'POPULAR',
    badgeColor: 'bg-gray-700',
    inStock: true,
    onSale: false,
    features: ['$20 USD', 'Instant Code', 'Global', 'All Games'],
    tags: ['steam', 'gaming', 'gift card', 'wallet']
  },
  {
    name: 'LinkedIn Learning 1 Month',
    description: 'Unlimited access to 16,000+ expert-led courses in business, tech, and creative skills. Earn certificates to showcase on your LinkedIn profile.',
    price: 299,
    originalPrice: 1400,
    category: 'Education',
    iconClass: 'fab fa-linkedin',
    iconColor: '#0a66c2',
    stock: 65,
    rating: 4.5,
    reviews: 780,
    badge: '-79%',
    badgeColor: 'bg-blue-600',
    inStock: true,
    onSale: true,
    features: ['16,000+ Courses', 'Certificates', 'Expert Led', 'All Topics'],
    tags: ['linkedin', 'learning', 'courses', 'education']
  },
  {
    name: 'McAfee Total Protection 1 Year',
    description: 'Award-winning antivirus with identity theft protection, secure VPN, password manager, and safe web browsing. Protects unlimited devices.',
    price: 399,
    originalPrice: 1299,
    category: 'Antivirus',
    iconClass: 'fas fa-shield-virus',
    iconColor: '#c01818',
    stock: 50,
    rating: 4.2,
    reviews: 950,
    badge: '-69%',
    badgeColor: 'bg-red-600',
    inStock: true,
    onSale: true,
    features: ['Unlimited Devices', 'VPN Included', 'ID Protection', 'Safe Browsing'],
    tags: ['mcafee', 'antivirus', 'security', 'vpn']
  }
];

const seedDB = async () => {
  try {
    await connectDB();
    await Product.deleteMany();
    await Product.insertMany(products);
    console.log('✅ Database seeded with', products.length, 'products');
    process.exit(0);
  } catch (err) {
    console.error('❌ Seeding error:', err.message);
    process.exit(1);
  }
};

seedDB();

